on: pull_request
name: hadolint action
jobs:
  hadolintOnPr:
    name: hadolint on pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tests
      runs: ./tests.sh
    - name: shellcheck
      uses: ludeeus/action-shellcheck@43d591f97276cf3883b8d6fd0341ecb1cc67142f
    - name: hadolintz
      uses: burdzwastaken/hadolint-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HADOLINT_ACTION_DOCKERFILE_FOLDER: .
